import {
  LayoutDashboard,
  Users,
  FileText,
  Settings,
  Bell,
  LogOut,
  Menu,
  X,
  User,
  Shield,
  Code,
  Map,
  UserCheck,
  BarChart3,
  TrendingUp,
  MapPin,
  Target,
  CreditCard,
  CheckCircle,
  FileBarChart,
  UserPlus,
  Upload,
  DollarSign,
  Building2,
  Briefcase,
  Calculator,
  Handshake,
  Receipt,
  FileSpreadsheet,
  BookOpen,
  Activity,
  Database,
  Monitor,
  HardDrive,
  Cpu,
  MemoryStick,
  Wifi,
  Clock,
  Calendar,
  Search,
  Filter,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Download,
  Save,
  RefreshCw,
  Home,
  Globe,
  Zap,
  Wrench, // Replaced Tool
  PieChart,
  LineChart,
  BarChart,
  Archive,
  Folder,
  FolderOpen,
  File,
  Image,
  Video,
  Music,
  Link,
  ExternalLink,
  Copy,
  Share,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Camera,
  Mic,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipForward, // Replaced Skip
  Repeat,
  Shuffle,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  Move,
  RotateCcw,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  Scissors,
  Paintbrush,
  Palette,
  Layers,
  Grid,
  List,
  Columns,
  Rows,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Type,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Indent,
  Outdent,
  ListOrdered,
  ListOrdered as ListUnordered, // Replaced ListUnordered
  Quote,
  Code2,
  Terminal,
  Command,
  Command as Option, // Replaced Option
  Command as Alt, // Replaced Alt
  Command as Shift, // Replaced Shift
  Command as Control, // Replaced Control
  ArrowLeft as Backspace, // Replaced Backspace
  Delete,
  CornerDownLeft,
  CornerDownLeft as Enter, // Replaced Enter
  Space,
  ArrowRight as Tab, // Replaced Tab
  X as Escape, // Replaced Escape
  Code2 as Function, // Replaced Function
  Camera as PrintScreen, // Replaced PrintScreen
  Plus as Insert, // Replaced Insert
  ChevronUp as PageUp, // Replaced PageUp
  ChevronDown as PageDown, // Replaced PageDown
  Square as End, // Replaced End
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight
} from 'lucide-react';

export const iconMap = {
  'layout-dashboard': LayoutDashboard,
  'users': Users,
  'file-text': FileText,
  'settings': Settings,
  'bell': Bell,
  'log-out': LogOut,
  'menu': Menu,
  'x': X,
  'chevron-down': ChevronDown,
  'user': User,
  'shield': Shield,
  'code': Code,
  'map': Map,
  'user-check': UserCheck,
  'bar-chart-3': BarChart3,
  'trending-up': TrendingUp,
  'map-pin': MapPin,
  'target': Target,
  'credit-card': CreditCard,
  'check-circle': CheckCircle,
  'file-bar-chart': FileBarChart,
  'user-plus': UserPlus,
  'upload': Upload,
  'dollar-sign': DollarSign,
  'activity': Activity,
  'building-2': Building2,
  'briefcase': Briefcase,
  'calculator': Calculator,
  'handshake': Handshake,
  'receipt': Receipt,
  'file-spreadsheet': FileSpreadsheet,
  'book-open': BookOpen,
  'database': Database,
  'monitor': Monitor,
  'hard-drive': HardDrive,
  'cpu': Cpu,
  'memory-stick': MemoryStick,
  'wifi': Wifi,
  'clock': Clock,
  'calendar': Calendar,
  'search': Search,
  'filter': Filter,
  'plus': Plus,
  'edit': Edit,
  'trash-2': Trash2,
  'eye': Eye,
  'eye-off': EyeOff,
  'download': Download,
  'save': Save,
  'refresh-cw': RefreshCw,
  'home': Home,
  'globe': Globe,
  'zap': Zap,
  'tool': Wrench,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  'bar-chart': BarChart,
  'archive': Archive,
  'folder': Folder,
  'folder-open': FolderOpen,
  'file': File,
  'image': Image,
  'video': Video,
  'music': Music,
  'link': Link,
  'external-link': ExternalLink,
  'copy': Copy,
  'share': Share,
  'heart': Heart,
  'thumbs-up': ThumbsUp,
  'message-circle': MessageCircle,
  'send': Send,
  'camera': Camera,
  'mic': Mic,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'play': Play,
  'pause': Pause,
  'skip': SkipForward,
  'repeat': Repeat,
  'shuffle': Shuffle,
  'maximize': Maximize,
  'minimize': Minimize,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'move': Move,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'flip-horizontal': FlipHorizontal,
  'flip-vertical': FlipVertical,
  'crop': Crop,
  'scissors': Scissors,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'layers': Layers,
  'grid': Grid,
  'list': List,
  'columns': Columns,
  'rows': Rows,
  'square': Square,
  'circle': Circle,
  'triangle': Triangle,
  'hexagon': Hexagon,
  'octagon': Octagon,
  'pentagon': Pentagon,
  'type': Type,
  'bold': Bold,
  'italic': Italic,
  'underline': Underline,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  'align-justify': AlignJustify,
  'indent': Indent,
  'outdent': Outdent,
  'list-ordered': ListOrdered,
  'list-unordered': ListOrdered,
  'quote': Quote,
  'code-2': Code2,
  'terminal': Terminal,
  'command': Command,
  'option': Command,
  'alt': Command,
  'shift': Command,
  'control': Command,
  'backspace': ArrowLeft,
  'delete': Delete,
  'enter': CornerDownLeft,
  'space': Space,
  'tab': ArrowRight,
  'escape': X,
  'function': Code2,
  'print-screen': Camera,
  'insert': Plus,
  'page-up': ChevronUp,
  'page-down': ChevronDown,
  'end': Square,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up': ChevronsUp,
  'chevrons-down': ChevronsDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight
};

export const getIcon = (iconName: string) => {
  return iconMap[iconName as keyof typeof iconMap] || iconMap['file'];
};

export default iconMap;
